import type { McpUniverseCategory, McpUniverseEntry } from "./types";

export const mcpUniverseLayers: { category: McpUniverseCategory; label: string; purpose: string }[] = [
  { category: "foundation", label: "Foundation", purpose: "Identity, secrets, repo, deployment, database, cloud, and storage." },
  { category: "intelligence", label: "Intelligence", purpose: "LLMs, model routers, embeddings, memory, reasoning, and evaluation." },
  { category: "discovery", label: "Discovery", purpose: "Market, web, trend, competitor, social, legal, funding, science, and patent research." },
  { category: "build", label: "Build", purpose: "Code, repo automation, tests, app builders, website builders, and browser automation." },
  { category: "validation", label: "Validation", purpose: "Tech, business, social, discovery, finance, legal, and health validation." },
  { category: "auto_heal", label: "Auto-Heal", purpose: "Error monitoring, incident detection, rollback recommendations, retry, and recovery." },
  { category: "auto_fix", label: "Auto-Fix", purpose: "Bug triage, patch drafting, config repair, workflow repair, and dependency fixes." },
  { category: "optimization", label: "Optimization", purpose: "Analytics, conversion, SEO, pricing, funnel, content, inventory, and ad optimization." },
  { category: "social", label: "Social Media", purpose: "Publishing, scheduling, analytics, comments, DMs, reviews, clipping, and repurposing." },
  { category: "content", label: "Content + Creative", purpose: "Copy, video, graphics, avatars, audio, brand kits, ads, and landing assets." },
  { category: "commerce", label: "Commerce", purpose: "Stores, payments, subscriptions, invoices, shipping, inventory, marketplaces, POS, and tax." },
  { category: "sales_crm", label: "Sales + CRM", purpose: "CRM, leads, enrichment, outbound, inbox, proposals, meetings, and pipeline." },
  { category: "customer_service", label: "Customer Service", purpose: "Tickets, chat, knowledge base, calls, sentiment, support automation, and escalation." },
  { category: "operations", label: "Operations", purpose: "SOPs, tasks, projects, calendars, procurement, field ops, dispatch, and supply chain." },
  { category: "finance", label: "Finance", purpose: "Accounting, bookkeeping, payroll, banking feeds, forecasting, expenses, and dashboards." },
  { category: "legal_compliance", label: "Legal + Compliance", purpose: "Contracts, e-signature, entity docs, privacy, security, and regulated-claims review." },
  { category: "hr_training", label: "HR + Training", purpose: "Hiring, onboarding, LMS, training content, employee docs, and certifications." },
  { category: "knowledge", label: "Knowledge", purpose: "Drive, docs, wikis, PDFs, sheets, vector memory, RAG, notes, and receipts." },
  { category: "industry_specific", label: "Industry-Specific", purpose: "Vertical tool packs for construction, ecommerce, real estate, healthcare, legal, education, and more." },
  { category: "governance", label: "Governance", purpose: "Approvals, permissions, audit, receipts, risk scoring, rollback, policy, human-in-loop, and cost controls." }
];

function credential(envName: string, minimumScope: string, required = true) {
  return {
    envName,
    secret: true,
    required,
    minimumScope,
    storageLocation: "Vercel encrypted env | GitHub secret | provider vault | external vault",
    rotation: "90d" as const
  };
}

const commonForbidden = ["unguarded production mutation", "secret exposure", "destructive delete without approval", "customer data export without approval"];

export const mcpUniverseRegistry: McpUniverseEntry[] = [
  {
    id: "github",
    name: "GitHub",
    category: "foundation",
    tier: "core",
    industryFit: ["universal"],
    priorityScore: 100,
    businessValueScore: 10,
    automationScore: 10,
    autonomyScore: 8,
    discoveryScore: 5,
    validationScore: 8,
    autoHealScore: 7,
    autoFixScore: 10,
    optimizationScore: 5,
    socialScore: 0,
    securityRiskScore: 8,
    blastRadius: "high",
    defaultMode: "supervised_write",
    maxAutonomyAllowed: "production_write_with_gate",
    requiredCredentials: [credential("GITHUB_TOKEN", "repo read, branch, PR, issue, workflow read")],
    connectedSystems: ["Vercel", "Codex", "GitHub Actions"],
    useCases: ["repo inspection", "branches", "PRs", "issues", "workflow logs", "source truth"],
    allowedAutonomousActions: ["read_repo", "read_file", "read_pr_status", "read_workflow_logs", "draft_issue", "draft_pr"],
    requiresApprovalActions: ["create_branch", "update_file", "commit", "push", "merge_pr", "workflow_dispatch"],
    forbiddenActions: ["force_push", "delete_repo", "disable_security", ...commonForbidden],
    validationTests: ["repo_read_smoke", "branch_safe_patch_dry_run", "workflow_log_read"],
    autoHealActions: ["inspect_failed_workflow", "draft_fix_issue"],
    autoFixActions: ["draft_patch", "draft_dependency_update", "open_branch_safe_pr_when_approved"],
    optimizationActions: ["rank_repo_gaps", "recommend_ci_hardening"],
    socialActions: [],
    loggingRequired: true,
    receiptType: "build",
    rollbackRequired: true,
    rollbackStrategy: "Revert PR or revert commit; protected branch merge requires approval.",
    costControls: ["limit workflow dispatch", "avoid paid runners unless approved"],
    rateLimits: ["GitHub API rate limits apply"],
    complianceNotes: ["Protected branch and authority-file rules remain active."],
    operatorNotes: ["Source truth code layer."]
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "foundation",
    tier: "core",
    industryFit: ["universal"],
    priorityScore: 99,
    businessValueScore: 10,
    automationScore: 10,
    autonomyScore: 8,
    discoveryScore: 2,
    validationScore: 9,
    autoHealScore: 8,
    autoFixScore: 7,
    optimizationScore: 8,
    socialScore: 0,
    securityRiskScore: 9,
    blastRadius: "high",
    defaultMode: "supervised_write",
    maxAutonomyAllowed: "production_write_with_gate",
    requiredCredentials: [credential("VERCEL_TOKEN", "project/deployment read, preview deploy, workflow read")],
    connectedSystems: ["GitHub", "Vercel Workflow", "Vercel Sandbox", "Vercel Agents"],
    useCases: ["deployments", "previews", "logs", "workflows", "cron pulse", "sandbox", "agents"],
    allowedAutonomousActions: ["read_deployments", "read_logs", "fetch_preview", "cron_readiness_check", "create_internal_receipt"],
    requiresApprovalActions: ["production_deploy", "env_mutation", "domain_alias", "rollback", "workflow_activation"],
    forbiddenActions: ["delete_project", "disable_protection", ...commonForbidden],
    validationTests: ["preview_smoke", "build_log_parse", "cron_dry_run"],
    autoHealActions: ["inspect_failed_deploy", "recommend_rollback", "draft_patch_task"],
    autoFixActions: ["draft_build_fix", "queue_preview_retest"],
    optimizationActions: ["speed_insight_review", "function_log_review"],
    socialActions: [],
    loggingRequired: true,
    receiptType: "system",
    rollbackRequired: true,
    rollbackStrategy: "Draft Vercel rollback recommendation; production rollback requires approval.",
    costControls: ["avoid production deploy loops", "do not widen env without approval"],
    rateLimits: ["Vercel API rate limits apply"],
    complianceNotes: ["Production deployment and env mutation remain guarded."],
    operatorNotes: ["Runtime, preview, workflow, sandbox, and agent surface."]
  },
  {
    id: "google_universe",
    name: "Google Cloud + Google Workspace Universe",
    category: "foundation",
    tier: "core",
    industryFit: ["universal", "local_services", "education", "ecommerce"],
    priorityScore: 98,
    businessValueScore: 10,
    automationScore: 9,
    autonomyScore: 7,
    discoveryScore: 9,
    validationScore: 8,
    autoHealScore: 6,
    autoFixScore: 5,
    optimizationScore: 9,
    socialScore: 8,
    securityRiskScore: 9,
    blastRadius: "critical",
    defaultMode: "supervised_write",
    maxAutonomyAllowed: "production_write_with_gate",
    requiredCredentials: [credential("GOOGLE_CLIENT_EMAIL", "Workspace/Cloud service account or OAuth scopes"), credential("GOOGLE_PRIVATE_KEY", "Workspace/Cloud service account private key")],
    connectedSystems: ["Drive", "Docs", "Sheets", "Gmail", "Calendar", "Keep", "Tasks", "Forms", "Cloud Run", "BigQuery", "Vertex AI", "YouTube", "Google Business Profile"],
    useCases: ["source truth", "documents", "sheets", "email drafts", "calendar", "tasks", "forms", "cloud jobs", "analytics", "local SEO", "YouTube"],
    allowedAutonomousActions: ["read_drive", "read_docs", "read_sheets", "draft_email", "draft_event", "read_cloud_status", "read_analytics", "create_internal_receipt"],
    requiresApprovalActions: ["send_email", "create_event", "share_file", "move_or_delete_file", "cloud_deploy", "secret_change", "youtube_publish"],
    forbiddenActions: ["delete_drive_canon_without_approval", "send_customer_email_without_approval", "change_iam_without_approval", ...commonForbidden],
    validationTests: ["workspace_readiness_check", "no_secret_output", "drive_receipt_dry_run"],
    autoHealActions: ["detect_stale_docs", "draft_cloud_repair", "flag_failed_workspace_job"],
    autoFixActions: ["draft_apps_script_fix", "draft_sheet_schema_fix", "draft_cloud_config_fix"],
    optimizationActions: ["search_console_review", "analytics_review", "business_profile_review"],
    socialActions: ["youtube_draft", "google_business_profile_draft"],
    loggingRequired: true,
    receiptType: "system",
    rollbackRequired: true,
    rollbackStrategy: "Use Drive revision history, cloud rollback, or draft reversal plan; live action approval required.",
    costControls: ["Cloud cost alerts", "BigQuery query budget", "AI/model spend caps"],
    rateLimits: ["Google API quota limits apply"],
    complianceNotes: ["Gmail, customer data, IAM, Vault, and regulated data require stricter review."],
    operatorNotes: ["Full Google ecosystem is first-class, including future Google tools."]
  },
  {
    id: "openai_gpt_business_ai_gateway",
    name: "OpenAI + GPT Business + AI Gateway",
    category: "intelligence",
    tier: "core",
    industryFit: ["universal"],
    priorityScore: 97,
    businessValueScore: 10,
    automationScore: 10,
    autonomyScore: 9,
    discoveryScore: 8,
    validationScore: 9,
    autoHealScore: 7,
    autoFixScore: 9,
    optimizationScore: 8,
    socialScore: 8,
    securityRiskScore: 8,
    blastRadius: "high",
    defaultMode: "draft",
    maxAutonomyAllowed: "production_write_with_gate",
    requiredCredentials: [credential("OPENAI_API_KEY", "model calls, evals, files/vector only when approved"), credential("AI_GATEWAY_API_KEY", "model routing and budget caps", false)],
    connectedSystems: ["Codex", "Vercel AI SDK", "OpenAI Files", "Vector Stores", "Batch", "Realtime", "Agents"],
    useCases: ["reasoning", "generation", "agent routing", "evaluations", "embeddings", "memory", "creative generation"],
    allowedAutonomousActions: ["draft", "classify", "summarize", "evaluate", "route_model_with_budget"],
    requiresApprovalActions: ["fine_tuning", "batch_large_spend", "external_claim_generation", "tool_widening"],
    forbiddenActions: ["unguarded_professional_advice_external_send", ...commonForbidden],
    validationTests: ["eval_check", "cost_receipt_check", "prompt_policy_check"],
    autoHealActions: ["classify_agent_failure", "draft_prompt_repair"],
    autoFixActions: ["draft_code_patch", "draft_eval_update"],
    optimizationActions: ["model_cost_review", "prompt_quality_review"],
    socialActions: ["draft_hooks", "draft_scripts", "draft_captions"],
    loggingRequired: true,
    receiptType: "system",
    rollbackRequired: false,
    rollbackStrategy: "Disable route or revert prompt/model config.",
    costControls: ["budget caps", "model route limits", "batch approval gate"],
    rateLimits: ["provider model limits apply"],
    complianceNotes: ["Human review required before regulated external claims."],
    operatorNotes: ["Core intelligence and GPT Business surface."]
  },
  {
    id: "social_distribution_universe",
    name: "All Social Media + Distribution Universe",
    category: "social",
    tier: "core",
    industryFit: ["universal", "creator_monetization", "local_services", "ecommerce", "agencies"],
    priorityScore: 96,
    businessValueScore: 10,
    automationScore: 9,
    autonomyScore: 6,
    discoveryScore: 10,
    validationScore: 8,
    autoHealScore: 7,
    autoFixScore: 5,
    optimizationScore: 10,
    socialScore: 10,
    securityRiskScore: 9,
    blastRadius: "high",
    defaultMode: "draft",
    maxAutonomyAllowed: "production_write_with_gate",
    requiredCredentials: [credential("METRICOOL_API_TOKEN", "social scheduling and analytics", false), credential("XYLA_API_KEY", "creative/social provider actions", false), credential("META_ACCESS_TOKEN", "Meta platform read/draft/write scopes", false)],
    connectedSystems: ["Metricool", "Xyla", "Facebook", "Instagram", "Threads", "TikTok", "YouTube", "Snapchat", "X", "LinkedIn", "Pinterest", "Reddit", "Discord", "Telegram", "WhatsApp Business", "GBP", "Yelp", "Trustpilot", "G2", "Capterra"],
    useCases: ["trend discovery", "content calendars", "draft posts", "caption generation", "analytics", "comments", "DM triage", "review monitoring", "repurposing"],
    allowedAutonomousActions: ["research_trends", "draft_post", "draft_calendar", "read_metrics", "classify_comments", "create_internal_social_queue"],
    requiresApprovalActions: ["publish_post", "send_dm", "reply_to_review", "ad_spend", "public_claim"],
    forbiddenActions: ["mass_outreach_without_approval", "regulated_claim_without_review", ...commonForbidden],
    validationTests: ["platform_format_check", "caption_length_check", "link_check", "policy_risk_check", "media_dimension_check"],
    autoHealActions: ["detect_failed_post", "draft_repost_plan", "flag_rate_limit"],
    autoFixActions: ["draft_replacement_post", "draft_schedule_repair"],
    optimizationActions: ["hook_variant_review", "publish_window_review", "topic_cluster_review"],
    socialActions: ["draft", "schedule_draft", "analytics_read", "sentiment_analysis"],
    loggingRequired: true,
    receiptType: "social",
    rollbackRequired: true,
    rollbackStrategy: "Delete/unpublish/repost plan requires platform-specific approval where live.",
    costControls: ["ad spend approval", "paid scheduling limits"],
    rateLimits: ["platform API and anti-spam limits apply"],
    complianceNotes: ["Public posting, DMs, reviews, and ads remain approval-gated unless governed campaign policy exists."],
    operatorNotes: ["All current and future social systems remain registry candidates."]
  },
  {
    id: "creator_monetization_universe",
    name: "Creator Monetization + Subscription Universe",
    category: "commerce",
    tier: "expansion",
    industryFit: ["creator_monetization", "universal"],
    priorityScore: 90,
    businessValueScore: 9,
    automationScore: 7,
    autonomyScore: 4,
    discoveryScore: 7,
    validationScore: 9,
    autoHealScore: 5,
    autoFixScore: 4,
    optimizationScore: 8,
    socialScore: 8,
    securityRiskScore: 10,
    blastRadius: "critical",
    defaultMode: "approval_required",
    maxAutonomyAllowed: "never_autonomous",
    requiredCredentials: [credential("CREATOR_PLATFORM_TOKEN", "platform-specific read/draft scopes", false)],
    connectedSystems: ["Fanvue", "Subs.com", "OnlyFans", "Patreon", "Substack", "Kajabi", "Teachable", "Thinkific", "Gumroad", "Lemon Squeezy", "Stripe", "PayPal"],
    useCases: ["subscription offers", "creator funnels", "content calendars", "membership analytics", "payment reconciliation"],
    allowedAutonomousActions: ["research_platform_rules", "draft_content_plan", "draft_offer", "read_metrics_when_allowed"],
    requiresApprovalActions: ["publish_content", "message_subscriber", "change_price", "payment_action", "identity_or_compliance_action"],
    forbiddenActions: ["age_restricted_action_without_review", "intimate_content_publish_without_approval", "payment_or_refund_without_approval", ...commonForbidden],
    validationTests: ["platform_policy_check", "age_compliance_check", "consent_check", "payment_gate_check"],
    autoHealActions: ["flag_failed_upload", "draft_policy_safe_replacement"],
    autoFixActions: ["draft_listing_fix", "draft_compliance_note"],
    optimizationActions: ["pricing_review_requires_approval", "churn_review", "offer_ladder_review"],
    socialActions: ["draft_teasers", "draft_calendar"],
    loggingRequired: true,
    receiptType: "commerce",
    rollbackRequired: true,
    rollbackStrategy: "Platform-specific reversal plan; live changes require approval.",
    costControls: ["payment/pricing approval", "paid promotion approval"],
    rateLimits: ["platform limits and policy restrictions apply"],
    complianceNotes: ["Adult, intimate, age-restricted, or sensitive platforms default to approval-required mode."],
    operatorNotes: ["Registry can include these platforms, but autonomy is intentionally lower due to risk." ]
  }
];

export const mcpUniverseCandidateGroups: Record<string, string[]> = {
  core_control: ["Git", "GitHub", "Vercel", "Supabase", "PostgreSQL", "Redis / Upstash", "Cloudflare", "Google Cloud", "Google Workspace", "Drive", "Gmail", "Docs", "Sheets", "Forms", "Keep", "Tasks", "Calendar", "Slack", "OpenAI", "Groq", "Codex", "AI Gateway", "Playwright", "Browserbase", "n8n"],
  google_full_stack: ["Google Cloud Platform", "Cloud Run", "Cloud Functions", "Cloud Storage", "Cloud Build", "Cloud Scheduler", "Cloud Tasks", "Pub/Sub", "Workflows", "Cloud SQL", "BigQuery", "Vertex AI", "Gemini", "IAM", "Secret Manager", "Drive", "Docs", "Sheets", "Slides", "Gmail", "Calendar", "Contacts", "Keep", "Tasks", "Forms", "Meet", "Chat", "Sites", "Groups", "Admin", "Vault", "Apps Script", "Looker Studio", "Analytics", "Search Console", "Tag Manager", "Ads", "Merchant Center", "Business Profile", "YouTube", "Play Console", "Classroom", "Maps Platform", "Places API", "Trends", "Alerts", "Patents", "Scholar"],
  ai_model_agent: ["OpenAI", "GPT Business", "Anthropic", "Gemini", "Groq", "Mistral", "Cohere", "Perplexity", "OpenRouter", "Ollama", "Hugging Face", "Replicate", "LangGraph", "LangChain", "LlamaIndex", "CrewAI", "AutoGen", "Vercel AI SDK", "Vercel Agents", "Vector database MCPs", "Evaluation MCPs", "Prompt registry MCPs"],
  social_distribution: ["Metricool", "Xyla", "Opus", "Buffer", "Hootsuite", "Sprout Social", "Later", "SocialBee", "Publer", "Taplio", "Facebook", "Instagram", "Threads", "TikTok", "YouTube", "YouTube Studio", "Snapchat", "X / Twitter", "LinkedIn", "Pinterest", "Reddit", "Discord", "Telegram", "WhatsApp Business", "Meta Business Suite", "Messenger", "Google Business Profile", "Yelp", "Trustpilot", "G2", "Capterra", "App Store Connect", "Google Play Console"],
  creator_monetization: ["Fanvue", "Subs.com", "OnlyFans", "Patreon", "Substack", "Kajabi", "Teachable", "Thinkific", "Gumroad", "Lemon Squeezy", "Paddle", "Stripe", "PayPal", "YouTube monetization", "TikTok creator monetization", "Meta monetization", "affiliate networks", "membership platforms", "paid communities"],
  creative: ["HeyGen", "Canva", "Figma", "Adobe Express", "Adobe Creative Cloud", "Photoshop", "Illustrator", "Premiere", "After Effects", "CapCut", "Descript", "Runway", "Pika", "Kling", "ElevenLabs", "Suno", "Udio", "OpusClip", "Riverside", "Frame.io", "Loom", "Synthesia", "D-ID", "Midjourney", "DALL-E", "Ideogram", "Leonardo", "Freepik", "Envato", "Unsplash", "Pexels", "Cloudinary", "ImageKit"],
  operations_knowledge: ["Notion", "ClickUp", "Asana", "Trello", "Monday.com", "Linear", "Jira", "Confluence", "Coda", "Airtable", "Smartsheet", "Basecamp", "Todoist", "Microsoft Planner", "Miro", "FigJam", "Lucidchart", "Whimsical", "Obsidian", "SharePoint", "Dropbox", "Box", "Slack", "Microsoft Teams", "Zoom"],
  commerce_payments: ["Shopify", "WooCommerce", "BigCommerce", "Amazon Seller Central", "Walmart Marketplace", "eBay", "Etsy", "TikTok Shop", "Google Merchant Center", "Meta Commerce Manager", "Stripe", "Square", "PayPal", "Paddle", "Lemon Squeezy", "Chargebee", "Recurly", "ShipStation", "Shippo", "EasyPost", "UPS", "FedEx", "DHL", "TaxJar", "Avalara", "QuickBooks Commerce", "Inventory Planner", "Klaviyo", "Attentive", "Postscript"]
};

export function getMcpUniverseRegistry() {
  return {
    version: "2026-06-08",
    system: "AUTO_BUILDER Universal MCP Max Autonomy Registry",
    noArtificialProviderLimit: true,
    governance: "Maximum catalog autonomy with approval gates for high-blast-radius actions.",
    layers: mcpUniverseLayers,
    registry: mcpUniverseRegistry,
    candidateGroups: mcpUniverseCandidateGroups
  };
}
