import { GlassCard, MobilePwaShell, StatusPill } from "@/components/mobile-pwa-shell";

export default function BuilderPage() {
  return (
    <MobilePwaShell title="Visual Builder" subtitle="Watch the system create the visible result in real time." active="Build">
      <GlassCard>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div><strong>Current Phase</strong><p style={{ margin: "6px 0 0", color: "rgba(255,255,255,.65)" }}>Build</p></div>
          <StatusPill>68%</StatusPill>
        </div>
        <div style={{ marginTop: 14, height: 8, borderRadius: 999, background: "rgba(255,255,255,.10)" }}><div style={{ width: "68%", height: "100%", borderRadius: 999, background: "#0A84FF", boxShadow: "0 0 24px rgba(10,132,255,.65)" }} /></div>
      </GlassCard>
      <GlassCard>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><strong>Preview</strong><StatusPill>Live</StatusPill></div>
        <section style={{ marginTop: 12, minHeight: 260, borderRadius: 18, border: "1px solid rgba(10,132,255,.35)", background: "radial-gradient(circle at 70% 45%, rgba(10,132,255,.35), transparent 30%), linear-gradient(135deg,#05101f,#02040a)", padding: 20, display: "grid", alignContent: "center" }}>
          <p style={{ color: "#53B9FF", textTransform: "uppercase", letterSpacing: 2, fontSize: 11 }}>Generated Homepage</p>
          <h2 style={{ margin: "8px 0", fontSize: 34, lineHeight: 1 }}>Find Your<br />Dream Home</h2>
          <p style={{ color: "rgba(255,255,255,.68)", maxWidth: 260 }}>AI-powered platform preview generated by the Builder Agent.</p>
          <button style={{ width: 145, marginTop: 14, border: 0, color: "white", background: "#0A84FF", padding: "12px 14px", borderRadius: 12 }}>Open Preview</button>
        </section>
      </GlassCard>
      <GlassCard>
        <strong>Build Activity</strong>
        {['Builder Agent: generating UI components', 'Frontend Agent: applying homepage layout', 'Validator Agent: checking visual score'].map((line) => <p key={line} style={{ color: "rgba(255,255,255,.70)", margin: "10px 0 0" }}>{line}</p>)}
      </GlassCard>
    </MobilePwaShell>
  );
}
